### ISSUE TITLE
Video and FCM: Add duration to FCMs and other videos

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-system#1073]
## Task

As part of #3086 (implement changes to FCM) and #3089 (adding duration, animation to FCM), we proposed adding a duration stamp to videos within the FCM. 

### Details

We're showing the runtime to better inform the viewer of what to expect when encountering a video. This would be shown as part of the overlay in a transparent box with white text, sitting in the bottom right corner of the video screenshot. The box would be the same gray color (with a multiply effect) as the play button, at least as dark as #757679 (66%K) for accessibility. The text would be at the same size as paragraph text. If the video length increases to double or triple digit minutes, the gray box would extend out to the left to fit those digits.

<img width="531" alt="Screen Shot 2020-10-02 at 11 30 31 AM" src="https://user-images.githubusercontent.com/6433178/94948530-77299800-04ad-11eb-8f64-73ed79a56fec.png">
<img width="463" alt="Screen Shot 2020-10-02 at 11 30 27 AM" src="https://user-images.githubusercontent.com/6433178/94948537-7a248880-04ad-11eb-80d9-eb83cad7de80.png">
<img width="657" alt="Screen Shot 2020-10-02 at 11 30 22 AM" src="https://user-images.githubusercontent.com/6433178/94948539-7abd1f00-04ad-11eb-8b7d-b59e59f49a5b.png">

* @designlanguage and @keelerr Worked on this before. The full history is at GHE/CFPB/hubcap/issues/97#issuecomment-182805

### Acceptance criteria
- [ ] Duration stamp implemented on FCMs 
- [ ] An evaluation is made about whether this time stamp should/can be implemented on other videos 

### Ready Checklist
- [ ] Has acceptance criteria or is part of a user story
- [ ] Describes the smallest possible chunk of work
- [ ] There are no blockers to starting the task
- [ ] All information necessary for completion is available
      - All input from other disciplines (Design/UX/Content/FEWD/BEWD) is attached
      - There are no outstanding questions for stakeholders

### Done Checklist
- [ ] All work has been peer-reviewed
- [ ] Has been acceptance tested and meets acceptance criteria
- [ ] All code or assets are merged to master
- [ ] All relevant documentation has been updated

**Comment by anselmbradford** [comment]
PR --> https://github.com/cfpb/consumerfinance.gov/pull/6267

Note the VideoPlayer code is not in the design system currently.
