### ISSUE TITLE
[Bug] Helper and placeholder text live code and specs don't match

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-system#1700]
Block helper, inline helper, and placeholder text do not match Design System specs

**Update:** 
- [ ] Helper text (block and inline) are 14px at mobile. They should be 16px. - This task is now captured here: https://github.com/cfpb/design-system/issues/1712
- [x] Placeholder text on the [texts input page](https://cfpb.github.io/design-system/components/text-inputs) needs a fix. I have documented the possible fixes [here](https://github.com/cfpb/design-system/issues/1700#issuecomment-1674623548).
- [ ] Date picker live code placeholder example is showing up as black instead of gray - This task is now captured here: https://github.com/cfpb/design-system/issues/1713

Related issue: 
- https://github.com/cfpb/design-system/issues/1709

**Design System styling:** 

 **Specs:** 
   - Avenir Next Regular, 16 px, Gray (#5a5d61)
 
 **Live code example:** 
   - Desktop: Avenir Next Regular, 16 px, Gray (#5a5d61) (for helper text) - correct
   - Mobile: Avenir Next Regular, 14 px, Gray (#5a5d61) (for helper text) - incorrect
   - Avenir Next Regular, 16 px, Black (#101820)(for placeholder text)

**To Reproduce**
- Steps to reproduce the behavior:
- 1. Go to 'https://cfpb.github.io/design-system/components/helper-text#types-1'
- 2. Click on ‘show details - specs’ for each of the 3 types
- 3. View live code examples
- 4. Compare to specs 

**Expected behavior**
- I expect the code to reflect the documented style specs 
- These 3 types of text should match in terms of size and color

**Resolution**
- Update block helper, inline helper and placeholder text to Avenir Next Regular, 16 px, Gray (#5a5d61)

@contolini @anselmbradford

**Comment by meissadia** [comment]
I do not see any mismatch between the specs and the font-sizes / colors.
 
## Block helper
font-size: 16px
font: Avenir Next
color: #5a5d61
<img width="354" alt="Screenshot 2023-08-10 at 3 08 13 PM" src="https://github.com/cfpb/design-system/assets/2592907/a2354ecb-f6a7-4337-8e51-8462c48439e0">

## Inline helper
font-size: 16px
font: Avenir Next
color: #5a5d61
<img width="384" alt="Screenshot 2023-08-10 at 3 08 21 PM" src="https://github.com/cfpb/design-system/assets/2592907/58e7eb3b-d153-4e19-85f9-696bc0ac1aeb">

## Placeholder
font-size: 16px
font: Avenir Next
color: Can't verify the color

<img width="1506" alt="Screenshot 2023-08-10 at 3 09 21 PM" src="https://github.com/cfpb/design-system/assets/2592907/46289399-6a55-4ab7-bdc5-9362f968cd8a">

**Comment by natalia-fitzgerald** [comment]
@anselmbradford - Do know what <small> is meant to do in the code for the block helper text and inline helper text?

**Comment by natalia-fitzgerald** [comment]
@meissadia 
If the inline helper, block helper, and placeholder are all set to 16px then that's good news. I inspected yesterday and got 14px but perhaps that was an error. If the only issue is the placeholder text being the wrong color then we can just handle the global update here: https://github.com/cfpb/design-system/issues/1702

**Comment by meissadia** [comment]
On CF.gov I see the placeholder set to the expected grey, not sure why this setting isn't coming through on the Design System doc pages

[cfpb-forms/src/atoms/text-input.less](https://github.com/cfpb/design-system/blob/main/packages/cfpb-forms/src/atoms/text-input.less#L83-L85)
```
::placeholder {
  color: #5a5d61;
}
```

**Comment by natalia-fitzgerald** [comment]
This is the page where the placeholder text is showing up as Black (#101820) instead of Gray.
https://cfpb.github.io/design-system/components/text-inputs
![Screenshot 2023-08-10 at 7 14 35 PM](https://github.com/cfpb/design-system/assets/77348967/ef7ce240-5d6e-48c7-af81-720c2282910b)

**Comment by natalia-fitzgerald** [comment]
Ok, I took another look and I think I see what’s happening. The text on the [text inputs page](https://cfpb.github.io/design-system/components/text-inputs) labels the input text as "placeholder text." But what it is actually showing stylistically is text that has been entered  by a user (that's why it's showing up in black). So, if this is the intent, we should change the wording of the text in the fields to better reflect what the live code is intended to show.

**Option 1.** If the example is intending to show text that a user has typed in the field we can use "User input text" or "Input text." I can also update the specs to include specs for both the placeholder text and the input text (shown below).  

| Current | Updated |
|------------|------------|
|<img width="934" alt="Screenshot 2023-08-11 at 12 17 11 AM" src="https://github.com/cfpb/design-system/assets/77348967/cc2d8a2e-26b4-4f61-9312-33522e6cd36a">|<img width="921" alt="Screenshot 2023-08-11 at 12 16 35 AM" src="https://github.com/cfpb/design-system/assets/77348967/58901f34-6111-4a45-afd5-85995002dbd7">|

**Option 2:** If the example is intending to show placeholder text we can change the code to make it show that. 
**Option 3:** Or we can leave the fields blank (this is what is done on USWDS). 
| Option 2: Placeholder text (Gray) | Option 3: Blank input fields |
|------------|------------|
|<img width="991" alt="Screenshot 2023-08-11 at 12 29 33 AM" src="https://github.com/cfpb/design-system/assets/77348967/86c68972-d07d-41b1-bc67-fa4f290700d4">|<img width="978" alt="Screenshot 2023-08-11 at 12 30 35 AM" src="https://github.com/cfpb/design-system/assets/77348967/c5ec7179-408d-47e2-a145-68879108ded7">|

Regardless of what we decide for the live code examples I'll update the specs to show the text styling for both placeholder and input text.

**Comment by natalia-fitzgerald** [comment]
@ans @meissadia 
I just had a realization. The 14px helper text that I originally identified happens at mobile. Because the helper text is set to a value relative to the size of the parent element (the label) and the parent element drops down in size at mobile the helper text is dropping down as well. The helper text should be 16px at all screen widths.

**Comment by natalia-fitzgerald** [comment]
I have now updated the specs content on the [text input page](https://cfpb.github.io/design-system/components/text-inputs) to include the text styling for both placeholder and input text.

We include the following guidelines for placeholder text: "Placeholder text appears within a text input field, and disappears once a user begins typing in that field. Use it for formatting examples only."

The examples we include are very much that - formatting examples. The examples that _were_ on the text input page (before I just published an edit) are not formatting examples. So, a question then is should we _generally_ default to no placeholder text unless there is a clear need that is a formatting example? Are there accessibility reasons for or against populating the placeholder text attribute?

**Comment by natalia-fitzgerald** [comment]
I have now updated the live code for the "Text input" page and it is displaying as described in [Option 1 ](https://github.com/cfpb/design-system/issues/1700#issuecomment-1674623548)(above). 

There is one more odd thing happening with the Date picker live code example where it shows placeholder text but is loading as Black. 
<img width="894" alt="Screenshot 2023-08-11 at 3 12 26 PM" src="https://github.com/cfpb/design-system/assets/77348967/6f9fc662-7e48-4fc9-9480-80fdce8c850c">

**Comment by natalia-fitzgerald** [comment]
I have moved the remaining tasks to their own issues: 
- Helper text (block and inline) are 14px at mobile. They should be 16px. - This task is now captured here: https://github.com/cfpb/design-system/issues/1712
- Date picker live code placeholder example is showing up as black instead of gray - This task is now captured here: https://github.com/cfpb/design-system/issues/1713

Closing this issue because the remaining tasks have been completed.
